# Format code with Google Java Format (https://github.com/google/google-java-format)
name: Format

on:
  push:
    branches:
      - master

jobs:

  formatting:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2 # v2 minimum required
      - uses: axel-op/googlejavaformat-action@v3
        # with:
        #   args: "--skip-sorting-imports --replace"
        # Recommended if you use MacOS:
        # githubToken: ${{ secrets.GITHUB_TOKEN }}
